config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  root 'home#index'
  resources :events
  resources :speakers

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, contraints: ApiConstraints.new(version: 1, default: true) do
      resources :events
      resources :speakers
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :talks, dependent: :destroy
  accepts_nested_attributes_for :talks, allow_destroy: true
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  belongs_to :event
  belongs_to :speaker
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ActionController::Base
      respond_to :json

      def index
        @events = Event.all
        events = Jbuilder.encode do |json|
          json.events @events do |event|
            json.id event.id
            json.title event.title
            json.description event.description
            json.event_date event.event_date

            json.talks event.talks do |talk|
              json.id talk.id
              json.title talk.title
              json.description talk.description
              json.speaker talk.speaker.name
              json.bio talk.speaker.bio
            end
          end
        end

        respond_with events
      end
    end
  end
end

app/controllers/api/v1/speakers_controller.rb
module Api
  module V1
    class SpeakersController < ActionController::Base
      respond_to :json

      def index
        @speakers = Speaker.all
        speakers = Jbuilder.encode do |json|
          json.speakers @speakers do |speaker|
            json.name speaker.name
            json.bio speaker.bio
          end
        end

        respond_with speakers
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @event.talks.build
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
      flash['success'] = 'Evento cadastrado com sucesso.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to events_path
      flash['success'] = 'Evento atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
    flash['success'] = 'Evento removido com sucesso.'
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :event_date,
                                  talks_attributes: [:id, :title, :description,
                                                     :speaker_id, :_destroy])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_action :set_speaker, only: [:edit, :update, :destroy]

  def index
    @speakers = Speaker.all
  end

  def new
    @speaker = Speaker.new
  end

  def create
    @speaker = Speaker.new(speaker_params)

    if @speaker.save
      redirect_to speakers_path
      flash['success'] = 'Palestrante cadastrado com sucesso.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @speaker.update(speaker_params)
      redirect_to speakers_path
      flash['success'] = 'Palestrante atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @speaker.destroy
    redirect_to speakers_path
    flash['success'] = 'Palestrante removido com sucesso.'
  end

  private

  def set_speaker
    @speaker = Speaker.find(params[:id])
  end

  def speaker_params
    params.require(:speaker).permit(:name, :bio, :gplus)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= simple_nested_form_for @event, defaults: { label: false} do |f| %>
  <div class='form-group'>
    <div class='row'>
      <div class='col-md-6'>
        <%= f.input :title, label: 'Nome do Evento', input_html: { class: 'form-control' } %>
      </div>
      <div class='col-md-6'>
        <%= f.input :event_date, as: :string, label: 'Data do Evento', input_html: { class: 'form-control datepicker' } %>
      </div>
    </div>
  </div>
  <div class='form-group'>
    <%= f.input :description, label: 'Descrição do Evento', input_html: { class: 'ckeditor' } %>
  </div>

  <h4 class='page-header'>Palestras</h4>
  <div class='form-group'>
    <%= f.simple_fields_for :talks do |t| %>
      <div class='row'>
        <div class='col-md-12'>
          <%= t.link_to_remove "Remover Palestra", class: 'btn btn-danger btn-xs' %>
        </div>
      </div>
      <%= render 'talks', t: t %>
    <% end %>
    <div class='row'>
      <div class='col-sm-12'>
        <p><%= f.link_to_add "Adicionar Palestra", :talks, class: 'btn btn-success btn-xs' %></p>
      </div>
    </div>
  </div>

  <div class='form-group'>
    <%= f.submit 'Salvar', class: 'btn btn-success' %>
    <%= link_to 'Voltar', events_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/events/_talks.html.erb
<div class='form-group'>
  <div class='row'>
    <div class='col-md-6'>
      <%= t.input :title, label: 'Título da Palestra', input_html: { class: 'form-control' } %>
    </div>
    <div class='col-md-6'>
      <%= t.association :speaker, label: 'Palestrante', label_method: :name, value_method: :id, include_blank: false, input_html: { class: 'form-control' } %>
    </div>
  </div>
</div>
<div class='form-group'>
  <%= t.input :description, as: :text, label: 'Descrição da Palestra', input_html: { class: 'form-control', rows: 3 } %>
</div>

app/views/events/edit.html.erb
<h3>Editar Evento</h3>
<hr/>
<%= render 'form' %>

app/views/events/index.html.erb
<h3>Eventos</h3>
<hr/>

<div class='col-md-12 text-right'>
  <%= link_to("Cadastrar Evento", new_event_path, class: "btn btn-primary") %>
</div>

<table class="table table-striped">
  <thead>
    <th></th>
    <th>Data do Evento</th>
    <th>Título</th>
    <th>Descrição</th>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td>
          <%= link_to("Editar", edit_event_path(event)) %>
          <%= link_to("Remover", event_path(event), method: :delete, data: { confirm: "Deseja remover o evento #{event.title}?" }) %>
        </td>
        <td><%= event.event_date %></td>
        <td><%= event.title %></td>
        <td><%= event.description.html_safe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h3>Cadastrar Evento</h3>
<hr/>
<%= render 'form' %>

app/views/home/index.html.erb
<div class='row'>
  <div class='col-md-12 text-center'>
    <%= image_tag 'android_jam_2.jpg', width: 1000 %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Navbar Template for Bootstrap</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body data-feedly-mini="yes">

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Android Jam</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to 'Eventos', events_path %></li>
              <li><%= link_to 'Palestrantes', speakers_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      <% flash.each do |key, f| %>
        <div class="alert alert-<%= key %>">
          <%= f %>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      <% end %>
      <%= yield %>
    </div> <!-- /container -->

    <style>.tb_button {padding:1px;cursor:pointer;border-right: 1px solid #8b8b8b;border-left: 1px solid #FFF;border-bottom: 1px solid #fff;}.tb_button.hover {borer:2px outset #def; background-color: #f8f8f8 !important;}.ws_toolbar {z-index:100000} .ws_toolbar .ws_tb_btn {cursor:pointer;border:1px solid #555;padding:3px}   .tb_highlight{background-color:yellow} .tb_hide {visibility:hidden} .ws_toolbar img {padding:2px;margin:0px}</style></body></html>

app/views/speakers/_form.html.erb
<%= simple_form_for @speaker, defaults: { label: false} do |f| %>
  <div class='form-group'>
    <div class='row'>
      <div class='col-md-6'>
        <%= f.input :name, label: 'Nome do Palestrante', input_html: { class: 'form-control' } %>
      </div>
      <div class='col-md-6'>
        <%= f.input :gplus, as: :string, label: 'Url do GooglePlus', input_html: { class: 'form-control' } %>
      </div>
    </div>
  </div>
  <div class='form-group'>
    <%= f.input :bio, as: :text, label: 'Bio do Palestrante', input_html: { class: 'form-control', rows: 4 } %>
  </div>

  <div class='form-group'>
    <%= f.submit 'Salvar', class: 'btn btn-success' %>
    <%= link_to 'Voltar', speakers_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/speakers/edit.html.erb
<h3>Editar Evento</h3>
<hr/>
<%= render 'form' %>

app/views/speakers/index.html.erb
<h3>Palestrantes</h3>
<hr/>

<div class='col-md-12 text-right'>
  <%= link_to("Cadastrar Palestrante", new_speaker_path, class: "btn btn-primary") %>
</div>

<table class="table table-striped">
  <thead>
    <th></th>
    <th>Nome</th>
    <th>Bio</th>
    <th>Url do GooglePlus</th>
  </thead>
  <tbody>
    <% @speakers.each do |speaker| %>
      <tr>
        <td>
          <%= link_to("Editar", edit_speaker_path(speaker)) %>
          <%= link_to("Remover", speaker_path(speaker), method: :delete, data: { confirm: "Deseja remover o palestrante #{speaker.name}?" }) %>
        </td>
        <td><%= speaker.name %></td>
        <td><%= speaker.bio %></td>
        <td><%= speaker.gplus %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/speakers/new.html.erb
<h3>Cadastrar Evento</h3>
<hr/>
<%= render 'form' %>